### PR TITLE
Fix id reference of visits

### LINKED ISSUE #136: Fixing id reference of visits
Each visit instance has two fields corresponding to the id of the person and location that it is referring to. Since location id and person id has been implemented, it is now appropriate to ensure that visit fields point to the right location and person id. The current implementation simply stores the user input directly. 

Note that the concept of id is abstracted away from the user, so the user is unaware of ids. Hence, a translation from the index of the user input to the right id is needed. The number being stored inside visits is the id of the person who is being referred to by the index given by the user.

### PR DESCRIPTION
**Pull request by hopinxian**
Implement a fix that ensures id of person and location that visit is referring to matches the intended person and location.

Fix #136

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java [hunk 1]
```diff
@@ -21,7 +27,7 @@
 public class AddVisitCommandTest {
     @Test
     public void constructor_nullLocation_throwsNullPointerException() {
-        assertThrows(NullPointerException.class, () -> new AddVisitCommand(null));
+        assertThrows(NullPointerException.class, () -> new AddVisitCommand(null, null, null));
```
Comment (siangernlow) [inline src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:30]: Now that there are three parameters for the constructors, perhaps it could be better if each parameter is tested for NullPointerException in a separate method.

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java [hunk 2]
```diff
@@ -21,7 +27,7 @@
 public class AddVisitCommandTest {
     @Test
     public void constructor_nullLocation_throwsNullPointerException() {
```
Comment (siangernlow) [inline src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:29]: Typo here. Shouldn't be nullLocation but instead the parameter that is null in this method.

File: src/main/java/seedu/address/logic/commands/AddVisitCommand.java [hunk 3]
```diff
@@ -28,33 +31,51 @@
...
 
     /**
      * Creates an AddVisitCommand to add the specified {@code Visit}
      */
-
-    public AddVisitCommand(Visit visit) {
-        requireAllNonNull(visit);
-        toAdd = visit;
+    public AddVisitCommand(Index personIndex, Index locationIndex, LocalDate date) {
+        requireAllNonNull(personIndex, locationIndex);
```
Comment (siangernlow) [inline src/main/java/seedu/address/logic/commands/AddVisitCommand.java:42]: Shouldn't date be required to be non null as well?

**Review by siangernlow — CHANGES_REQUESTED** [review]
Changes requested, certain tests need to be added as mentioned.

Also, are there tests to test if the issue of adding the wrong index has been solved? Having a test which tests if the same visit is added based on what the viewer sees should be added if it does not exist yet.

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java (hunk 1 above)
Comment (hopinxian) [reply src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:30]: Have added additional assertions.

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java (hunk 2 above)
Comment (hopinxian) [reply src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:29]: Have changed the method name

File: src/main/java/seedu/address/logic/commands/AddVisitCommand.java (hunk 3 above)
Comment (hopinxian) [reply src/main/java/seedu/address/logic/commands/AddVisitCommand.java:42]: Thanks for the catch! I have updated it.

**Comment by hopinxian** [comment]
Thanks for the review. I have improved the Pull Request according to your comments.

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java [hunk 4]
```diff
@@ -4,43 +4,96 @@
...
+        Index personId = model.getFilteredPersonList().get(0).getId();
+        Index locationId = model.getFilteredLocationList().get(0).getId();
+        Visit validVisit = new VisitBuilder().withDate(DEFAULT_DATE_STRING)
+                .withLocationId(Integer.toString(locationId.getOneBased()))
+                .withPersonId(Integer.toString(personId.getOneBased()))
+                .build();
+
+        try {
+            new AddVisitCommand(INDEX_FIRST, INDEX_FIRST, DEFAULT_DATE).execute(model);
+            assertEquals(model.getFilteredVisitList().get(0), validVisit);
```
Comment (KohHanMing) [inline src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:86]: Just a thought, shouldn't the validVisit be created based on the hard coded locationId INDEX_THIRD and personId INDEX_FOURTH? Right now valid visit still references the filtered list. If there's an error in the translation of ids between filtered list and the original lists, the test would still pass as both the AddVisitCommand and validVisit would have made the same error.

**Review by KohHanMing — CHANGES_REQUESTED** [review]
Almost done! I think one test case just needs a little bit of tweaking.

**Review by siangernlow — APPROVED** [review]

File: src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java (hunk 4 above)
Comment (hopinxian) [reply src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:86]: This copy of valid visit is hard coded, by using the visit builder class. The hard coded values are retrieved using the getOneBased method. Valid visit has no direct reference to filtered visit at all.

The gist of this test is that my model's filtered lists for person and location currently store only 1 location with id 3 and 1 person with id 4. This is done using the showLocationAtIndex, showPersonAtIndex methods above. Im giving the model input using index 1 and index 1 for person and location, because the list user sees contains only 1 element. After processing however, I am expecting the visit to point to ids 3 and 4 respectively. This is done by comparing the final visit from the visit list with the expected visit created using valid visit.

Comment (KohHanMing) [reply src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java:86]: I see, no issue then!

**Review by KohHanMing — APPROVED** [review]
